"""add_finance_module

Revision ID: 1baae518e560
Revises: 6fde2351c883
Create Date: 2026-03-14 23:26:21.809920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1baae518e560'
down_revision: Union[str, Sequence[str], None] = '6fde2351c883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_tax_templates',
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'template_name', name='uq_fin_tax_template_name')
    )
    op.create_index(op.f('ix_fin_tax_templates_tenant_id'), 'fin_tax_templates', ['tenant_id'], unique=False)
    op.create_table('fin_tax_template_lines',
    sa.Column('tax_template_id', sa.UUID(), nullable=False),
    sa.Column('tax_name', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_inclusive', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tax_template_id'], ['fin_tax_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_tax_template_lines_tenant_id'), 'fin_tax_template_lines', ['tenant_id'], unique=False)
    op.create_table('fin_clients',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('currency_id', sa.UUID(), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['hr_companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['hr_currencies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_clients_tenant_id'), 'fin_clients', ['tenant_id'], unique=False)
    op.create_table('fin_exchange_rate_configs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('auto_fetch', sa.Boolean(), nullable=True),
    sa.Column('api_provider', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['hr_companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_fin_exchange_rate_configs_tenant_id'), 'fin_exchange_rate_configs', ['tenant_id'], unique=False)
    op.create_table('fin_quotes',
    sa.Column('docstatus', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('quote_number', sa.String(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exchange_rate_locked', sa.Boolean(), nullable=True),
    sa.Column('tax_template_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('base_total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['fin_clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['hr_companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['hr_currencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_template_id'], ['fin_tax_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_quotes_tenant_id'), 'fin_quotes', ['tenant_id'], unique=False)
    op.create_table('fin_tds_configs',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('is_applicable', sa.Boolean(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('threshold_annual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('accumulated_payments_this_year', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['fin_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_fin_tds_configs_tenant_id'), 'fin_tds_configs', ['tenant_id'], unique=False)
    op.create_table('fin_proforma_invoices',
    sa.Column('docstatus', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('proforma_number', sa.String(), nullable=True),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exchange_rate_locked', sa.Boolean(), nullable=True),
    sa.Column('tax_template_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('base_total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['fin_clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['hr_companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['hr_currencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['fin_quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_template_id'], ['fin_tax_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_proforma_invoices_tenant_id'), 'fin_proforma_invoices', ['tenant_id'], unique=False)
    op.create_table('fin_quote_line_items',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_sac_code', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_template_id', sa.UUID(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['fin_quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_template_id'], ['fin_tax_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_quote_line_items_tenant_id'), 'fin_quote_line_items', ['tenant_id'], unique=False)
    op.create_table('fin_invoices',
    sa.Column('docstatus', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('proforma_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exchange_rate_locked', sa.Boolean(), nullable=True),
    sa.Column('tax_template_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('base_total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('outstanding_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tds_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['fin_clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['hr_companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['hr_currencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proforma_id'], ['fin_proforma_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['fin_quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_template_id'], ['fin_tax_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_invoices_tenant_id'), 'fin_invoices', ['tenant_id'], unique=False)
    op.create_table('fin_proforma_line_items',
    sa.Column('proforma_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_sac_code', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_template_id', sa.UUID(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['proforma_id'], ['fin_proforma_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_template_id'], ['fin_tax_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_proforma_line_items_tenant_id'), 'fin_proforma_line_items', ['tenant_id'], unique=False)
    op.create_table('fin_invoice_line_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_sac_code', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_template_id', sa.UUID(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['fin_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_template_id'], ['fin_tax_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_invoice_line_items_tenant_id'), 'fin_invoice_line_items', ['tenant_id'], unique=False)
    op.create_table('fin_payments',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_received', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('tds_deducted', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tds_section', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('exchange_rate_at_payment', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['fin_invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_payments_tenant_id'), 'fin_payments', ['tenant_id'], unique=False)
    op.create_table('fin_recurring_invoice_configs',
    sa.Column('template_invoice_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('custom_interval_days', sa.Integer(), nullable=True),
    sa.Column('next_run_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auto_submit', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_date', sa.Date(), nullable=True),
    sa.Column('total_generated', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['template_invoice_id'], ['fin_invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_recurring_invoice_configs_tenant_id'), 'fin_recurring_invoice_configs', ['tenant_id'], unique=False)
    op.add_column('hr_companies', sa.Column('gstin', sa.String(length=15), nullable=True, comment='GST Identification Number. 15-char alphanumeric. Required for Indian GST compliance on invoices.'))
    op.add_column('hr_companies', sa.Column('state_code', sa.String(length=2), nullable=True, comment='Two-letter Indian state code for CGST/SGST vs IGST determination. e.g. MH=Maharashtra, KA=Karnataka. Leave null for non-Indian companies.'))
    op.add_column('hr_companies', sa.Column('base_currency_id', sa.UUID(), nullable=True, comment="The company's reporting currency. All invoice amounts are converted to this currency for financial reporting."))
    op.create_foreign_key(None, 'hr_companies', 'hr_currencies', ['base_currency_id'], ['id'], ondelete='SET NULL')

    # Manual Addition: Audit FKs and RLS for all 13 finance tables
    new_tables = [
        "fin_tax_templates", "fin_tax_template_lines", "fin_clients",
        "fin_exchange_rate_configs", "fin_quotes", "fin_tds_configs",
        "fin_proforma_invoices", "fin_quote_line_items", "fin_invoices",
        "fin_proforma_line_items", "fin_invoice_line_items", "fin_payments",
        "fin_recurring_invoice_configs"
    ]
    for table in new_tables:
        op.create_foreign_key(
            f"fk_{table}_created_by", table, "hr_users",
            ["created_by"], ["id"], ondelete="SET NULL"
        )
        op.create_foreign_key(
            f"fk_{table}_modified_by", table, "hr_users",
            ["modified_by"], ["id"], ondelete="SET NULL"
        )
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_constraint(None, 'hr_companies', type_='foreignkey')
    op.drop_column('hr_companies', 'base_currency_id')
    op.drop_column('hr_companies', 'state_code')
    op.drop_column('hr_companies', 'gstin')
    op.drop_index(op.f('ix_fin_recurring_invoice_configs_tenant_id'), table_name='fin_recurring_invoice_configs')
    op.drop_table('fin_recurring_invoice_configs')
    op.drop_index(op.f('ix_fin_payments_tenant_id'), table_name='fin_payments')
    op.drop_table('fin_payments')
    op.drop_index(op.f('ix_fin_invoice_line_items_tenant_id'), table_name='fin_invoice_line_items')
    op.drop_table('fin_invoice_line_items')
    op.drop_index(op.f('ix_fin_proforma_line_items_tenant_id'), table_name='fin_proforma_line_items')
    op.drop_table('fin_proforma_line_items')
    op.drop_index(op.f('ix_fin_invoices_tenant_id'), table_name='fin_invoices')
    op.drop_table('fin_invoices')
    op.drop_index(op.f('ix_fin_quote_line_items_tenant_id'), table_name='fin_quote_line_items')
    op.drop_table('fin_quote_line_items')
    op.drop_index(op.f('ix_fin_proforma_invoices_tenant_id'), table_name='fin_proforma_invoices')
    op.drop_table('fin_proforma_invoices')
    op.drop_index(op.f('ix_fin_tds_configs_tenant_id'), table_name='fin_tds_configs')
    op.drop_table('fin_tds_configs')
    op.drop_index(op.f('ix_fin_quotes_tenant_id'), table_name='fin_quotes')
    op.drop_table('fin_quotes')
    op.drop_index(op.f('ix_fin_exchange_rate_configs_tenant_id'), table_name='fin_exchange_rate_configs')
    op.drop_table('fin_exchange_rate_configs')
    op.drop_index(op.f('ix_fin_clients_tenant_id'), table_name='fin_clients')
    op.drop_table('fin_clients')
    op.drop_index(op.f('ix_fin_tax_template_lines_tenant_id'), table_name='fin_tax_template_lines')
    op.drop_table('fin_tax_template_lines')
    op.drop_index(op.f('ix_fin_tax_templates_tenant_id'), table_name='fin_tax_templates')
    op.drop_table('fin_tax_templates')
    # ### end Alembic commands ###
