"""add_salary_structure_to_employee

Revision ID: 248c9afb5df7
Revises: b670d0398687
Create Date: 2026-03-12 04:57:24.840726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248c9afb5df7'
down_revision: Union[str, Sequence[str], None] = 'b670d0398687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_employees', sa.Column('salary_structure_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'hr_employees', 'hr_salary_structures', ['salary_structure_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hr_employees', type_='foreignkey')
    op.drop_column('hr_employees', 'salary_structure_id')
    # ### end Alembic commands ###
