"""Add LeaveType and LeaveApplication

Revision ID: 3abef1e5ef82
Revises: 6c861c64b3e1
Create Date: 2026-02-27 11:19:29.956489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abef1e5ef82'
down_revision: Union[str, Sequence[str], None] = '6c861c64b3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_leave_types',
    sa.Column('leave_type_name', sa.String(), nullable=False),
    sa.Column('max_leaves_allowed', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('applicable_after', sa.Integer(), nullable=True),
    sa.Column('max_continuous_days_allowed', sa.Integer(), nullable=True),
    sa.Column('is_carry_forward', sa.Boolean(), nullable=False),
    sa.Column('maximum_carry_forwarded_leaves', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expire_carry_forwarded_leaves_after_days', sa.Integer(), nullable=True),
    sa.Column('is_lwp', sa.Boolean(), nullable=False),
    sa.Column('is_ppl', sa.Boolean(), nullable=False),
    sa.Column('fraction_of_daily_salary_per_leave', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_optional_leave', sa.Boolean(), nullable=False),
    sa.Column('allow_negative', sa.Boolean(), nullable=False),
    sa.Column('allow_over_allocation', sa.Boolean(), nullable=False),
    sa.Column('include_holiday', sa.Boolean(), nullable=False),
    sa.Column('is_compensatory', sa.Boolean(), nullable=False),
    sa.Column('allow_encashment', sa.Boolean(), nullable=False),
    sa.Column('max_encashable_leaves', sa.Integer(), nullable=True),
    sa.Column('non_encashable_leaves', sa.Integer(), nullable=True),
    sa.Column('is_earned_leave', sa.Boolean(), nullable=False),
    sa.Column('earned_leave_frequency', sa.String(), nullable=True),
    sa.Column('allocate_on_day', sa.String(), nullable=True),
    sa.Column('rounding', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_leave_types_leave_type_name'), 'hr_leave_types', ['leave_type_name'], unique=True)
    op.create_index(op.f('ix_hr_leave_types_tenant_id'), 'hr_leave_types', ['tenant_id'], unique=False)
    op.create_table('hr_leave_applications',
    sa.Column('docstatus', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('naming_series', sa.String(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('leave_approver_id', sa.UUID(), nullable=True),
    sa.Column('amended_from_id', sa.UUID(), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('half_day', sa.Boolean(), nullable=False),
    sa.Column('half_day_date', sa.Date(), nullable=True),
    sa.Column('total_leave_days', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('leave_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('follow_via_email', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['amended_from_id'], ['hr_leave_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['hr_companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leave_approver_id'], ['hr_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['hr_leave_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_leave_applications_company_id'), 'hr_leave_applications', ['company_id'], unique=False)
    op.create_index(op.f('ix_hr_leave_applications_employee_id'), 'hr_leave_applications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_leave_applications_leave_approver_id'), 'hr_leave_applications', ['leave_approver_id'], unique=False)
    op.create_index(op.f('ix_hr_leave_applications_leave_type_id'), 'hr_leave_applications', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_hr_leave_applications_tenant_id'), 'hr_leave_applications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_leave_applications_tenant_id'), table_name='hr_leave_applications')
    op.drop_index(op.f('ix_hr_leave_applications_leave_type_id'), table_name='hr_leave_applications')
    op.drop_index(op.f('ix_hr_leave_applications_leave_approver_id'), table_name='hr_leave_applications')
    op.drop_index(op.f('ix_hr_leave_applications_employee_id'), table_name='hr_leave_applications')
    op.drop_index(op.f('ix_hr_leave_applications_company_id'), table_name='hr_leave_applications')
    op.drop_table('hr_leave_applications')
    op.drop_index(op.f('ix_hr_leave_types_tenant_id'), table_name='hr_leave_types')
    op.drop_index(op.f('ix_hr_leave_types_leave_type_name'), table_name='hr_leave_types')
    op.drop_table('hr_leave_types')
    # ### end Alembic commands ###
