"""add_rbac_user_roles_org_scope

Revision ID: 6fde2351c883
Revises: 248c9afb5df7
Create Date: 2026-03-14 20:18:41.340046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fde2351c883'
down_revision: Union[str, Sequence[str], None] = '248c9afb5df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_role_permissions',
    sa.Column('role', sa.String(), nullable=False, comment='One of: owner, hr_manager, finance_manager, manager, employee, auditor'),
    sa.Column('module', sa.String(), nullable=False, comment='One of: hrms, payroll, finance, settings, crm, tasks'),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_submit', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'role', 'module', name='uq_role_permission_per_tenant')
    )
    op.create_index(op.f('ix_hr_role_permissions_module'), 'hr_role_permissions', ['module'], unique=False)
    op.create_index(op.f('ix_hr_role_permissions_role'), 'hr_role_permissions', ['role'], unique=False)
    op.create_index(op.f('ix_hr_role_permissions_tenant_id'), 'hr_role_permissions', ['tenant_id'], unique=False)
    op.add_column('hr_users', sa.Column('hashed_password', sa.String(), nullable=True, comment='Bcrypt hashed password. Nullable because invite flow sets password after account creation.'))
    op.add_column('hr_users', sa.Column('role', sa.String(), nullable=True, comment='One of: owner, hr_manager, finance_manager, manager, employee, auditor'))
    op.execute("UPDATE hr_users SET role = 'owner' WHERE role IS NULL")
    op.alter_column('hr_users', 'role', nullable=False)
    op.add_column('hr_users', sa.Column('company_id', sa.UUID(), nullable=True, comment='Which company this user belongs to within the tenant.'))
    op.add_column('hr_users', sa.Column('employee_id', sa.UUID(), nullable=True, comment='The employee record for this user. Null for owner accounts created before an employee record exists.'))
    op.add_column('hr_users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Last successful login timestamp. Used for seat activity tracking.'))
    op.create_index(op.f('ix_hr_users_company_id'), 'hr_users', ['company_id'], unique=False)
    op.create_foreign_key(None, 'hr_users', 'hr_companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_user_employee_id', 'hr_users', 'hr_employees', ['employee_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###

    # --- Manual Additions: Audit FKs ---
    TABLES_NEEDING_AUDIT_FK = [
       "hr_companies", "hr_employees", "hr_leave_applications",
       "hr_attendance", "hr_attendance_requests",
       "hr_salary_slips", "hr_salary_structures",
       "hr_salary_components", "hr_compliance_settings",
       "hr_role_permissions"
    ]

    for table in TABLES_NEEDING_AUDIT_FK:
        op.create_foreign_key(
            f"fk_{table}_created_by",
            table, "hr_users",
            ["created_by"], ["id"],
            ondelete="SET NULL"
        )
        op.create_foreign_key(
            f"fk_{table}_modified_by",
            table, "hr_users",
            ["modified_by"], ["id"],
            ondelete="SET NULL"
        )

    # --- Manual Additions: RLS for hr_role_permissions ---
    op.execute("ALTER TABLE hr_role_permissions ENABLE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON hr_role_permissions
        USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
    """)

    # --- Manual Additions: Seed Default Permissions ---
    # Default Permissions Matrix as defined in app.utils.permissions
    DEFAULT_PERMISSIONS = {
        "owner": {
            "hrms":     {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": True},
            "payroll":  {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": True},
            "finance":  {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": True},
            "settings": {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": True},
            "crm":      {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": True},
            "tasks":    {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": True},
        },
        "hr_manager": {
            "hrms":     {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": True},
            "payroll":  {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": False},
            "finance":  {"view": False, "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "settings": {"view": True,  "create": False, "edit": True,  "submit": False, "approve": False, "delete": False},
            "crm":      {"view": False, "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "tasks":    {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": False},
        },
        "finance_manager": {
            "hrms":     {"view": False, "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "payroll":  {"view": True,  "create": False, "edit": False, "submit": False, "approve": True,  "delete": False},
            "finance":  {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": True},
            "settings": {"view": True,  "create": False, "edit": True,  "submit": False, "approve": False, "delete": False},
            "crm":      {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": False},
            "tasks":    {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": False},
        },
        "manager": {
            "hrms":     {"view": True,  "create": False, "edit": False, "submit": False, "approve": True,  "delete": False},
            "payroll":  {"view": False, "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "finance":  {"view": False, "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "settings": {"view": False, "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "crm":      {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": False, "delete": False},
            "tasks":    {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": True,  "delete": False},
        },
        "employee": {
            "hrms":     {"view": True,  "create": False, "edit": False, "submit": True,  "approve": False, "delete": False},
            "payroll":  {"view": True,  "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "finance":  {"view": False, "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "settings": {"view": False, "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "crm":      {"view": False, "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "tasks":    {"view": True,  "create": True,  "edit": True,  "submit": True,  "approve": False, "delete": False},
        },
        "auditor": {
            "hrms":     {"view": True,  "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "payroll":  {"view": True,  "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "finance":  {"view": True,  "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "settings": {"view": True,  "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "crm":      {"view": True,  "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
            "tasks":    {"view": True,  "create": False, "edit": False, "submit": False, "approve": False, "delete": False},
        },
    }

    test_tenant_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    import uuid
    from datetime import datetime, timezone

    for role, modules in DEFAULT_PERMISSIONS.items():
        for module, actions in modules.items():
            op.execute(
                sa.text(
                    "INSERT INTO hr_role_permissions "
                    "(id, tenant_id, role, module, can_view, can_create, can_edit, can_submit, can_approve, can_delete, created_at, updated_at) "
                    "VALUES (:id, :tenant_id, :role, :module, :can_view, :can_create, :can_edit, :can_submit, :can_approve, :can_delete, :created_at, :updated_at)"
                ).bindparams(
                    id=str(uuid.uuid4()),
                    tenant_id=test_tenant_id,
                    role=role,
                    module=module,
                    can_view=actions["view"],
                    can_create=actions["create"],
                    can_edit=actions["edit"],
                    can_submit=actions["submit"],
                    can_approve=actions["approve"],
                    can_delete=actions["delete"],
                    created_at=datetime.now(timezone.utc),
                    updated_at=datetime.now(timezone.utc)
                )
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_employee_id', 'hr_users', type_='foreignkey')
    op.drop_constraint(None, 'hr_users', type_='foreignkey')
    op.drop_index(op.f('ix_hr_users_company_id'), table_name='hr_users')
    op.drop_column('hr_users', 'last_login')
    op.drop_column('hr_users', 'employee_id')
    op.drop_column('hr_users', 'company_id')
    op.drop_column('hr_users', 'role')
    op.drop_column('hr_users', 'hashed_password')
    op.drop_index(op.f('ix_hr_role_permissions_tenant_id'), table_name='hr_role_permissions')
    op.drop_index(op.f('ix_hr_role_permissions_role'), table_name='hr_role_permissions')
    op.drop_index(op.f('ix_hr_role_permissions_module'), table_name='hr_role_permissions')
    op.drop_table('hr_role_permissions')
    # ### end Alembic commands ###
