"""add_payroll_module

Revision ID: b670d0398687
Revises: 6d9c6c44b3e2
Create Date: 2026-03-12 04:28:07.010666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b670d0398687'
down_revision: Union[str, Sequence[str], None] = '6d9c6c44b3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_professional_tax_slabs',
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('min_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pt_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_february', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_professional_tax_slabs_tenant_id'), 'hr_professional_tax_slabs', ['tenant_id'], unique=False)
    op.create_table('hr_salary_components',
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('component_type', sa.String(length=20), nullable=False),
    sa.Column('is_statutory', sa.Boolean(), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'component_name', name='uq_salary_component_name')
    )
    op.create_index(op.f('ix_hr_salary_components_tenant_id'), 'hr_salary_components', ['tenant_id'], unique=False)
    op.create_table('hr_compliance_settings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('pf_applicable', sa.Boolean(), nullable=False),
    sa.Column('esi_applicable', sa.Boolean(), nullable=False),
    sa.Column('pt_applicable', sa.Boolean(), nullable=False),
    sa.Column('tds_applicable', sa.Boolean(), nullable=False),
    sa.Column('pf_wage_ceiling', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('esi_gross_ceiling', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['hr_companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_hr_compliance_settings_tenant_id'), 'hr_compliance_settings', ['tenant_id'], unique=False)
    op.create_table('hr_salary_structures',
    sa.Column('structure_name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['hr_companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_salary_structures_tenant_id'), 'hr_salary_structures', ['tenant_id'], unique=False)
    op.create_table('hr_salary_structure_components',
    sa.Column('salary_structure_id', sa.UUID(), nullable=False),
    sa.Column('salary_component_id', sa.UUID(), nullable=False),
    sa.Column('calculation_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['salary_component_id'], ['hr_salary_components.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['hr_salary_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salary_structure_id', 'salary_component_id', name='uq_structure_component')
    )
    op.create_index(op.f('ix_hr_salary_structure_components_tenant_id'), 'hr_salary_structure_components', ['tenant_id'], unique=False)
    op.create_table('hr_salary_slips',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('salary_structure_id', sa.UUID(), nullable=True),
    sa.Column('payroll_month', sa.Integer(), nullable=False),
    sa.Column('payroll_year', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('present_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gross_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_employee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pf_employer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('eps_employer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('esi_employee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('esi_employer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('docstatus', sa.Integer(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['hr_companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['hr_salary_structures.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'employee_id', 'payroll_month', 'payroll_year', name='uq_salary_slip_period')
    )
    op.create_index(op.f('ix_hr_salary_slips_tenant_id'), 'hr_salary_slips', ['tenant_id'], unique=False)
    op.create_table('hr_salary_slip_deductions',
    sa.Column('salary_slip_id', sa.UUID(), nullable=False),
    sa.Column('salary_component_id', sa.UUID(), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['salary_component_id'], ['hr_salary_components.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_slip_id'], ['hr_salary_slips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_salary_slip_deductions_tenant_id'), 'hr_salary_slip_deductions', ['tenant_id'], unique=False)
    op.create_table('hr_salary_slip_earnings',
    sa.Column('salary_slip_id', sa.UUID(), nullable=False),
    sa.Column('salary_component_id', sa.UUID(), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['salary_component_id'], ['hr_salary_components.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_slip_id'], ['hr_salary_slips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_salary_slip_earnings_tenant_id'), 'hr_salary_slip_earnings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    
    # RLS Policies
    tables = [
        'hr_compliance_settings',
        'hr_professional_tax_slabs',
        'hr_salary_components',
        'hr_salary_structures',
        'hr_salary_structure_components',
        'hr_salary_slips',
        'hr_salary_slip_deductions',
        'hr_salary_slip_earnings'
    ]
    
    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID)
            WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true)::UUID)
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_salary_slip_earnings_tenant_id'), table_name='hr_salary_slip_earnings')
    op.drop_table('hr_salary_slip_earnings')
    op.drop_index(op.f('ix_hr_salary_slip_deductions_tenant_id'), table_name='hr_salary_slip_deductions')
    op.drop_table('hr_salary_slip_deductions')
    op.drop_index(op.f('ix_hr_salary_slips_tenant_id'), table_name='hr_salary_slips')
    op.drop_table('hr_salary_slips')
    op.drop_index(op.f('ix_hr_salary_structure_components_tenant_id'), table_name='hr_salary_structure_components')
    op.drop_table('hr_salary_structure_components')
    op.drop_index(op.f('ix_hr_salary_structures_tenant_id'), table_name='hr_salary_structures')
    op.drop_table('hr_salary_structures')
    op.drop_index(op.f('ix_hr_compliance_settings_tenant_id'), table_name='hr_compliance_settings')
    op.drop_table('hr_compliance_settings')
    op.drop_index(op.f('ix_hr_salary_components_tenant_id'), table_name='hr_salary_components')
    op.drop_table('hr_salary_components')
    op.drop_index(op.f('ix_hr_professional_tax_slabs_tenant_id'), table_name='hr_professional_tax_slabs')
    op.drop_table('hr_professional_tax_slabs')
    # ### end Alembic commands ###
